"""Recreate downloads table

Revision ID: 5fdda0f5dbab
Revises: 15b64eeaede8
Create Date: 2025-05-08 08:17:37.658566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fdda0f5dbab'
down_revision: Union[str, None] = '15b64eeaede8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'downloads',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('user_id', sa.Integer, nullable=False),
        sa.Column('video_id', sa.Integer, nullable=False),
        sa.Column('result', sa.String, nullable=False),
        sa.Column('confidence', sa.Float, nullable=False),
        sa.Column('file_name', sa.String, nullable=True),
        sa.Column('download_count', sa.Integer, nullable=False, server_default='0'),
        sa.Column('timestamp', sa.DateTime, server_default=sa.func.now(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
